### UserPlants Index
GET http://localhost:3000/user_plants.json

### Create User Plant
POST http://localhost:3000/user_plants.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE3MDA4MjgzMDZ9.woohRwo2ZyvH0DYUWaEWxvuW_vGDEDW3jYZKQCgYRr4

{
  "name": "Mican",
  "plant_id": 1,
  "zone_id": 1,
  "type_id": 1,
  "img_url": "test.jpg"
}

###Show Action
GET http://localhost:3000/user_plants/2.json

### Update Action
PATCH http://localhost:3000/user_plants/2.json
Content-Type: application/json

{
  "name": "ppp"
}

### Destroy Action
DELETE http://localhost:3000/user_plants/2.json

### User Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Smith",
  "email": "john@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions Create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "john@test.com",
  "password": "password"
}

### Testing API
GET http://localhost:3000/care_instructions/3.json