### UserPlants Index
GET http://localhost:3000/user_plants.json

### Create User Plant
POST http://localhost:3000/user_plants.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE3MDEyNTg3NjF9.cNIMlVAtEuFUSgsoR1srco3QXsuFzKvaYHFHR9oMrbo

{
  "name": "Philodendron",
  "zone_id": 1,
  "type_id": 1,
  "img_url": "test.jpg"
}

### UserPlant Index Action
GET http://localhost:3000/user_plants.json

###Show Action
GET http://localhost:3000/user_plants/3.json

### Update Action
PATCH http://localhost:3000/user_plants/2.json
Content-Type: application/json

{
  "name": "ppp"
}

### Destroy Action
DELETE http://localhost:3000/user_plants/2.json

### User Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Smith",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions Create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "john@test.com",
  "password": "password"
}

### CareInstruction Show
GET http://localhost:3000/care_instructions.json

### Testing API
GET http://localhost:3000/care_instructions/3.json

### CareInstructions Index
GET http://localhost:3000/care_instructions.json

### Cuttings Index
GET http://localhost:3000/watering_schedules.json

### Cuttings Create
POST http://localhost:3000/cuttings.json
Content-Type: application/json

{
  "user_plant_id": 3,
  "zone_id": 1,
  "date_cut": 1,
  "roots": true
}

### Cuttings Update
PATCH http://localhost:3000/cuttings/2.json
Content-Type: application/json

{
  "roots": false
}

### Watering Schedule Create
POST http://localhost:3000/watering_schedules.json
Content-Type: application/json

{
  "user_plant_id": 3,
  "schedule": "Water when dry."
}

### Types Index
GET http://localhost:3000/types.json

### FertilizerSchedule Create
PATCH http://localhost:3000/fertilizer_schedules/1.json
Content-Type: application/json

{
  "schedule": "Feed every week."
}

###FertilizerSchedule Destroy
DELETE http://localhost:3000/fertilizer_schedules/1.json

### Zone Create
POST http://localhost:3000/zones.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE3MDE0Nzg0Nzd9.8YupIyfa1jQemiRhUZZMbOQv1l1_3d-G3QPFy7oT09I

{
  "location_name": "Kitchen",
  "light_level": "low"
}

###Zone Update
PATCH http://localhost:3000/zones/1.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE3MDEyNTg3NjF9.cNIMlVAtEuFUSgsoR1srco3QXsuFzKvaYHFHR9oMrbo

{
  "light_level": "high"
}

###Details Test
GET http://localhost:3000/details/monstera.json

### Dropdowns test
GET http://localhost:3000/dropdowns/plant.json

### Search test
GET http://localhost:3000/search.json
