json.id user_plant.id
json.user_id user_plant.user_id
json.plant_id user_plant.plant_id
json.zone_id user_plant.zone_id
json.type_id user_plant.type_id
json.name user_plant.name
json.img_url user_plant.img_url
json.get_watering_instructions user_plant.get_watering_instructions
json.created_at user_plant.created_at
json.updated_at user_plant.updated_at
