json.id user_plant.id
json.user_id user_plant.user_id
json.type_name user_plant.type_name
json.name user_plant.name
json.watering_schedules user_plant.watering_schedules
json.care_instructions user_plant.care_instructions
json.created_at user_plant.created_at
json.updated_at user_plant.updated_at
json.zone_name user_plant.zone_name
